name: data updates from https://www.mise.gov.it

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '15 */3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
    - name: Verifica aggiornamenti
      run: |-
        git pull
        wget https://www.mise.gov.it/images/exportCSV/anagrafica_impianti_attivi.csv
        wget https://www.mise.gov.it/images/exportCSV/prezzo_alle_8.csv
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "iXMapsBot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Datetime: ${timestamp}" || exit 0
        git push
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
