name: data updates from https://strutturericettive.turismo.marche.it

on:
  push:
  repository_dispatch:
  schedule:
    - cron: '15 8 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
    - name: Verifica aggiornamenti
      working-directory: ./open data marche
      run: |-
        git pull
        wget -O turismo_marche_IstriceRoss1000_ElencoStrutture.json https://strutturericettive.turismo.marche.it/api/IstriceRoss1000/ElencoStrutture
    - name: Committa e pusha se ci sono variazioni nei dati
      working-directory: ./open data marche
      run: |-
        git config user.name "iXMapsBot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Datetime: ${timestamp}" || exit 0
        git push
